#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    setxkbmap -v us -option > /dev/null
elif [[ "$OSTYPE" == "darwin"* ]]; then
    xkbswitch -s 0
else
    echo "Unhandled operating system $OSTYPE"
fi
 
