#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    setxkbmap -v real-prog-dvorak -option ctrl:nocaps > /dev/null
elif [[ "$OSTYPE" == "darwin"* ]]; then
    xkbswitch -s 4
else
    echo "Unhandlde operating system $OSTYPE"
fi


