#!/usr/bin/env bash

echo https://nixpk.gs/pr-tracker.html?pr=338836
echo TRY TO REMOVE DEPENDENCIES ON nixpkgs/master
set -e
pushd ~/.dotfiles
find . | grep "\.nix" | xargs git diff
echo "NixOS Rebuilding..."
nixos-rebuild switch --flake .#nixos-dt --use-remote-sudo
gen=$(nixos-rebuild list-generations | grep current)
find . | grep "\.nix" | xargs git add
git commit -m "$gen"
popd
