#!/usr/bin/env bash
echo https://nixpk.gs/pr-tracker.html?pr=338836
echo TRY TO REMOVE DEPENDENCIES ON nixpkgs/master
set -e
pushd ~/.dotfiles
find . | grep "\.nix" | xargs git diff
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake .#nixos-dt &>nixos-switch.log || (
 cat nixos-switch.log | grep --color error && false)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
popd
