#!/usr/bin/env bash
# AUTHOR: ThePrimeagen
#
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    dirs="~ ~/projects/ ~/work"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    dirs="~/ ~/projects ~/work ~/Dropbox/Documents"
else
    echo "Unhandled operating system $OSTYPE"
    exit 1
fi

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(eval find -L $dirs -mindepth 1 -maxdepth 1 -type d,l | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
