#!/usr/bin/env bash
# AUTHOR: ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find -L ~/Dropbox/Documents ~/projects ~/ -mindepth 1 -maxdepth 1 -type d,l | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
zellij_running=$(pgrep zellij)

# zellij attach --create $selected_name options --default-cwd $selected
zellij pipe --plugin "file:/Users/bmoffett/.dotfiles/zellij/plugins/zellij-switch.wasm" -- "--session $selected_name --cwd $selected"
